spring:
  datasource:
    username: "sa"
    password: ""
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
